import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthWrapper from "@/library/next.auth.wrapper";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ReduxProviderWrapper from "@/library/redux.provider.wrapper";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" style={{ margin: 0, padding: 0 }}>
            <body
                className={`${geistSans.variable} ${geistMono.variable}`}
                style={{ margin: 0, padding: 0 }}
            >
                <AntdRegistry>
                    <NextAuthWrapper>
                        <ReduxProviderWrapper>
                            {children}
                        </ReduxProviderWrapper>
                    </NextAuthWrapper>
                </AntdRegistry>
            </body>
        </html>
    );
}
