export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"
export const RESET_REGISTER_STATE = "RESET_REGISTER_STATE"
export const UPDATE_REGISTER_FORM = "UPDATE_REGISTER_FORM"

export const CHECK_INSURANCE_REQUEST = "CHECK_INSURANCE_REQUEST"
export const CHECK_INSURANCE_SUCCESS = "CHECK_INSURANCE_SUCCESS"
export const CHECK_INSURANCE_NOT_FOUND = "CHECK_INSURANCE_NOT_FOUND"
export const CHECK_INSURANCE_FAILURE = "CHECK_INSURANCE_FAILURE"

export const CHECK_PATIENT_EXIST_REQUEST = "CHECK_PATIENT_EXIST_REQUEST"
export const CHECK_PATIENT_EXIST_FAILURE = "CHECK_PATIENT_EXIST_FAILURE"
export const CHECK_PATIENT_EXIST_NOT_FOUND = "CHECK_PATIENT_EXIST_NOT_FOUND"
export const CHECK_PATIENT_EXIST_SUCCESS = "CHECK_PATIENT_EXIST_SUCCESS"


export const CLEAR_REGISTER_ERROR = "CLEAR_REGISTER_ERROR"
export const CLEAR_INSURANCE_CHECK = "CLEAR_INSURANCE_CHECK"
export const CLEAR_INSURANCE_ERROR = "CLEAR_INSURANCE_ERROR"
export const CLEAR_PATIENT_EXIST_CHECK = "CLEAR_PATIENT_EXIST_CHECK"